### ISSUE TITLE
Fails to build on aarch64, armv7, powerpc*

### ISSUE THREAD

**Issue by jbeich** [shssoichiro/ffmpeg-the-third#63]
Regressed by #38. According to [LLDB CharIsSignedByDefault()](https://github.com/llvm/llvm-project/blob/cc2fafa1788908f69366821a04407083f770483e/lldb/source/Utility/ArchSpec.cpp#L712-L736) and [FreeBSD arch(7)](https://man.freebsd.org/arch/7) on some platforms `char` is `unsigned`. From [error log](https://pkg-status.freebsd.org/ampere2/data/main-arm64-default/pd65a728b53a9_scadd2ca2176/logs/errors/av1an-0.4.2_4.log):

```rust
$ cargo build --target aarch64-unknown-freebsd
[...]
error[E0308]: mismatched types
  --> src/util/channel_layout/channel_custom.rs:27:13
   |
27 |             name,
   |             ^^^^ expected `[u8; 16]`, found `[i8; 16]`
   |
   = note: expected array `[u8; 16]`
              found array `[i8; 16]`
```

**Comment by FreezyLemon** [comment]
It's unfortunate that CI didn't catch this. I don't think GitHub Actions has arm-based runners outside of macOS, but maybe we can at least add a build-only check.

**Comment by FreezyLemon** [comment]
Fixed by #64
